Extra error handling

diff --git a/regtest b/regtest
--- a/regtest
+++ b/regtest
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [ "$1" == "" ]; then
-  echo "Please specify 'start', 'stop', 'build', 'clean' or other bitcoin-cli command"
+  echo "Please specify 'start', 'stop', 'clean' or other bitcoin-cli command"
   exit 1
 fi
 
@@ -9,49 +9,64 @@ DIR="$HOME/.bitcoin-sv-regtest"
 
 # Build is commented out as we are using an official image from dockerhub
 
-if [ "$1" == "build" ]; then
-  cat <<EOF | docker build --no-cache -t bitcoin-sv -
-ARG PLATFORM=linux/amd64
-FROM --platform=\$PLATFORM ubuntu:20.04
+# if [ "$1" == "build" ]; then
+#   cat <<EOF | docker build --no-cache -t bitcoin-sv -
+# ARG PLATFORM=linux/amd64
+# FROM --platform=\$PLATFORM ubuntu:20.04
 
-RUN set -x \
-  &&  apt-get update \
-  && apt-get -y install wget libatomic1 \
-  && rm -rf /var/lib/apt/lists/*
+# RUN set -x \
+#   &&  apt-get update \
+#   && apt-get -y install wget libatomic1 \
+#   && rm -rf /var/lib/apt/lists/*
 
-RUN set -x \
-  && cd /tmp \
-  && wget -qO bitcoin.tar.gz https://download.bitcoinsv.io/bitcoinsv/1.0.16/bitcoin-sv-1.0.16-x86_64-linux-gnu.tar.gz \
-  && tar -xzvf bitcoin.tar.gz -C /usr/local --strip-components=1 --exclude=*-qt \
-  && rm -rf /tmp/*
+# RUN set -x \
+#   && cd /tmp \
+#   && wget -qO bitcoin.tar.gz https://download.bitcoinsv.io/bitcoinsv/1.0.16/bitcoin-sv-1.0.16-x86_64-linux-gnu.tar.gz \
+#   && tar -xzvf bitcoin.tar.gz -C /usr/local --strip-components=1 --exclude=*-qt \
+#   && rm -rf /tmp/*
 
-RUN set -x \
-  && echo '#!/bin/sh' > /entrypoint.sh \
-  && echo 'shift' >> /entrypoint.sh \
-  && echo 'bitcoind -datadir=/data \$@' >> /entrypoint.sh \
-  && chmod +x /entrypoint.sh
+# RUN set -x \
+#   && echo '#!/bin/sh' > /entrypoint.sh \
+#   && echo 'shift' >> /entrypoint.sh \
+#   && echo 'bitcoind -datadir=/data \$@' >> /entrypoint.sh \
+#   && chmod +x /entrypoint.sh
 
-ENTRYPOINT ["/entrypoint.sh"]
-EOF
-  exit $?
-fi
+# ENTRYPOINT ["/entrypoint.sh"]
+# EOF
+#   exit $?
+# fi
 
 if [ "$1" == "clean" ]; then
-  if $(docker ps -a | grep -q bitcoin-sv-regtest); then
-    echo "bitcoin-sv-regtest container is running, stop before cleaning."
+  if docker ps | grep -q bitcoin-sv-regtest; then
+    echo "ERROR: bitcoin-sv-regtest container is running, stop before cleaning."
     exit 1
   fi
+
+  # This command removes the Docker container named 'bitcoin-sv-regtest'
+  # The '-v' flag ensures that any associated volumes are also removed
+  # This is useful for cleaning up resources when you no longer need the container
+  docker rm -v bitcoin-sv-regtest > /dev/null 2>&1
 
   rm -rf $DIR
   exit 0
 fi
 
 if [ "$1" == "stop" ]; then
+  if ! docker ps | grep -q bitcoin-sv-regtest; then
+    echo "ERROR: bitcoin-sv-regtest container is not running."
+    exit 1
+  fi
+
   docker exec bitcoin-sv-regtest bitcoin-cli -datadir=/data stop
   exit 0
 fi
 
 if [ "$1" == "start" ]; then
+  if docker ps | grep -q bitcoin-sv-regtest; then
+    echo "ERROR: bitcoin-sv-regtest container is already running."
+    exit 1
+  fi
+
   mkdir -p $DIR
 
   if [ -L "$0" ]; then 
